export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const CHANGE_MENU_TITLE = "CHANGE_MENU_TITLE";
export const PUSH_ERROR = "PUSH_ERROR";
export const MODIFY_LOADER = "MODIFY_LOADER";
export const CHANGE_DELIVERY = "CHANGE_DELIVERY";

export const DECREMENT_FROM_ORDER = "DECREMENT_FROM_ORDER";
export const INCREMENT_TO_ORDER = "INCREMENT_TO_ORDER";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const CHANGE_ORDER = "CHANGE_ORDER";
export const DELETE_FROM_ORDER = "DELETE_FROM_ORDER";

export const GET_ACTION = "GET_ACTION";