export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const CHANGE_MENU_TITLE = "CHANGE_MENU_TITLE";
export const PUSH_ERROR = "PUSH_ERROR";
export const MODIFY_LOADER = "MODIFY_LOADER";
export const CHANGE_DELIVERY = "CHANGE_DELIVERY";

export const DECREMENT_FROM_ORDER = "DECREMENT_FROM_ORDER";
export const INCREMENT_TO_ORDER = "INCREMENT_TO_ORDER";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const CHANGE_ORDER = "CHANGE_ORDER";
export const DELETE_FROM_ORDER = "DELETE_FROM_ORDER";

export const CHANGE_ADDRESSES = "CHANGE_ADDRESSES";
export const ADD_ADDRESS = "ADD_ADDRESS";

export const CHANGE_MY_ORDERS = "CHANGE_MY_ORDERS";
export const ADD_TO_MY_ORDERS = "ADD_TO_MY_ORDERS";

export const GET_ORDER_STATUSES = "GET_ORDER_STATUSES";